# Generated by Django 3.2.16 on 2024-03-22 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_auto_20240321_1424'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscriptions',
        ),
    ]
