# Generated by Django 4.2.11 on 2024-03-30 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriptions',
            options={'ordering': ('-author_id',), 'verbose_name': 'подписка', 'verbose_name_plural': 'Подписки'},
        ),
    ]
